server:
  port: 9194

spring:
  application:
    name: PAYMENT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/payment_service?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultzone: http://localhost:8761/eureka/
  instance:
    hostname: localhost